import { createSlice } from '@reduxjs/toolkit';

// Create the slice using RTK
const counterSlice = createSlice({
  name: 'counter',
  initialState: {
    value: 0, // Initial counter value
  },
  reducers: {
    // Reducer to increment the counter
    increment: (state) => {
      state.value += 1;
    },
    // Reducer to decrement the counter
    decrement: (state) => {
      state.value -= 1;
    },
  },
});

// Export actions generated by createSlice
export const { increment, decrement } = counterSlice.actions;

// Export the reducer, which will be used to configure the store
export default counterSlice.reducer;
